apiVersion: v1
clusters:
- cluster:
    server: https://api.yourcluster.com:6443  # From command above
    certificate-authority-data: LS0tLS1CRUdJTi...  # From command above
  name: cluster-access-cluster
contexts:
- context:
    cluster: cluster-access-cluster
    user: cluster-access-sa
    namespace: cluster-access
  name: cluster-access-context
current-context: cluster-access-context
kind: Config
users:
- name: cluster-access-sa
  user:
    token: eyJhbGciOiJSUzI1NiIs...  # From token extraction command
